### ISSUE TITLE
Cannot import pydbg with Python 2.7.2

### ISSUE THREAD

**Issue by ciphor** [OpenRCE/paimei#2]
I installed pydbg with the following steps: (OS is WinXP, python 2.7.2)
1. Download pydasm from http://code.google.com/p/libdasm/downloads/detail?name=libdasm-beta.zip&can=2&q=
2. Unzip pydasm, and enter the dir of pydasm
     python setup.py build_ext --compiler=mingw32
     python setup.py install
3. Download paimei&pydbg from github
4. Unzip paimei&pydbg, and copy the files of pydbg to the pydbg/ sub directory of paimei
5. Enter the dir of paimei,
    python setup.py build
    python setup.py install

All above steps finished successfully, but when I try to import pydbg module, failure occurs:

> > > import pydbg

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import pydbg
  File "C:\Python27\lib\site-packages\pydbg__init__.py", line 47, in <module>
    from pydbg                   import *
  File "C:\Python27\lib\site-packages\pydbg\pydbg.py", line 32, in <module>
    import pydasm
ImportError: Module use of python26.dll conflicts with this version of Python.

Does this mean that pydbg can only work with python 2.6?

**Comment by juntalis** [comment]
This occurs because the compiled version of the pydasm extension they're using is for python 2.6. To fix this, just compile [libdasm](http://code.google.com/p/libdasm/) and build the extension with your version of Python. If you don't have a compiler on hand or don't know how to do this, I have some compiled binaries I can send you.
